#!/bin/sh

UKERNELS="linux linux-fallback"

kernels_build() {
	report_stage "Building unified kernels"

	UCODE_IMG=$(ls /boot | grep ucode.img | head -n 1)
	
	for i in $UKERNELS; do
		INITRAMFS="/boot/initramfs-$i.img"
		if [ -n "$UCODE_IMG" ]; then
			report_start "Creating new $i with ucode: $UCODE_IMG"
			ce "cat /boot/$UCODE_IMG /boot/initramfs-$i.img > /tmp/initramfs-linux.img"
			INITRAMFS="/tmp/initramfs-linux.img"	
		fi
		report_start "Creating $i unified kernel image"

		(mkdir -p /boot/EFI/Linux || true) 2>/dev/null
		chmod -R 755 /boot/EFI
		ce "objcopy \
--add-section .osrel=\"/usr/lib/os-release\" --change-section-vma .osrel=0x20000 \
--add-section .linux=\"/boot/vmlinuz-linux\" --change-section-vma .linux=0x2000000 \
--add-section .initrd=\"$INITRAMFS\" --change-section-vma .initrd=0x3000000 \
\"/usr/lib/systemd/boot/efi/linuxx64.efi.stub\" \"/boot/EFI/Linux/$i.efi\""
		[ -n "$UCODE_IMG" ] && rm $INITRAMFS
		report_success
	done
}

kernels_sign() {
	report_stage "Signing unified kernels"

	prompt_existing_passphrase
	report_start "Temporarily decrypting db key"
	cd /etc/efi-keys
	ce "openssl rsa -in db.key -passin stdin -out /tmp/db.key <<EOF
$PASS
EOF"
	for i in $UKERNELS; do
		report_start "Signing $i unified kernel"
		ce "sbsign --key /tmp/db.key --cert db.crt --output /boot/EFI/Linux/$i.efi /boot/EFI/Linux/$i.efi"
		report_success
	done
	clean_tmp_keys
}

kernels_remove() {
	report_start "Removing unified kernels"
	for i in $UKERNELS; do
		rm /boot/EFI/Linux/$i.efi 2>/dev/null
	done
	report_success
}

KERN_USAGE_MSG="$BANNER

USAGE: $(basename $0) unified-kernel <subcommand> [-v]

SUBCOMMANDS:
	build - Build unified kernels including initramfs and ucode
	sign - Sign the unified kernels
	setup - Perform all of the above 
	remove - Remove unified kernels
"

handle_unified_kernel() {
	case "$1" in
		build) kernels_build;;
		sign) kernels_sign;;
		setup) kernels_build && kernels_sign;;
		remove) kernels_remove;;
		*) >&2 echo "$KERN_USAGE_MSG"
	esac	
}
