#!/bin/sh

PROC_DIR="$(dirname $0)"
INC_DIR="/usr/share/sbsimple"

source_helper() {
	if [ -f "$PROC_DIR/sbsimple-$1" ]; then
		. "$PROC_DIR/sbsimple-$1"
	else
		. "$INC_DIR/sbsimple-$1"
	fi
}

source_helper "common"
source_helper "keys"
source_helper "unified-kernel"
source_helper "grub"
source_helper "pacman"

USAGE_MSG="$BANNER

USAGE: $(basename $0) <subcommand>

SUBCOMMANDS:
	keys - Secure boot key operations
	grub - GRUB bootloader operations
	pacman - Arch/Pacman install hook operations
	setup - Create secure boot setup for standard Arch distribution
	unified-kernel - Unified kernel operations
	remove - Remove secure boot setup
"

([ "$3" = "-v" ] || [ "$2" = "-v" ]) && VERBOSE="1"
[ "$(id -u)" != 0 ] && >&2 echo "Run as root." && exit 1

case "$1" in
	keys) handle_keys "$2";;
	unified-kernel) handle_unified_kernel "$2";;
	grub) handle_grub "$2";;
	pacman) handle_pacman "$2";;
	setup) handle_keys setup && handle_unified_kernel setup && \
		handle_grub setup && handle_pacman setup;;
	remove) pacman_remove && kernels_remove && keys_remove && \
		grub_remove && \
		echo "Since GRUB was removed, you must run grub-install to reinstall GRUB";;
	*) >&2 echo "$USAGE_MSG"
esac

