#!/bin/sh

source $(dirname $0)/sbsimple-common
source $(dirname $0)/sbsimple-keys
source $(dirname $0)/sbsimple-unified-kernel

USAGE_MSG="$BANNER

USAGE: $0 <subcommand>

SUBCOMMANDS:
	keys - Secure boot key operations
	grub - GRUB bootloader operations
	pacman - Arch/Pacman install hook operations
	setup - Create secure boot setup for standard Arch distribution
	unified-kernel - Unified kernel operations
"

[ "$3" = "-v" ] && VERBOSE="1"
[ "$(id -u)" != 0 ] && >&2 echo "Run as root." && exit 1

case "$1" in
	keys) handle_keys "$2";;
	unified-kernel) handle_unified_kernel "$2";;
	*) >&2 echo "$USAGE_MSG"
esac
